### ISSUE TITLE
Datenbank bearbeiten 

### ISSUE THREAD

**Issue by Jules96** [Dziersan/WebTech_Themenverwaltung2.0#9]
/estimated 

- einheitliche Nomenklatur
- Normalisierung
- einheitliche Sprache: Englisch

**Comment by Jules96** [comment]
/estimated 4 Stunden 

- einheitliche Nomenklatur
- einheitliche Sprache: Englisch
- Datenbank überarbeiten

**Comment by tecnot2773** [comment]
started in a432890688ad8d2f3293c847cf9bd2e9f2437610
